# Generated by Django 2.0.6 on 2018-06-16 22:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tym', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_institution', models.CharField(max_length=200)),
                ('adress_institution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.IntegerField()),
                ('count_ticket', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular ticket across whole event', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('f', 'Free'), ('b', 'Booked'), ('s', 'Sold')], default='f', help_text='Book availability', max_length=1)),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number_ticket', models.IntegerField()),
                ('cost_ticket', models.DecimalField(decimal_places=2, max_digits=7)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tym.Event')),
                ('status_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tym.Status_ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Type_institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.TextField()),
                ('password_user', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tym.Type_ticket'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tym.Ticket'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tym.Type_payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tym.User'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tym.Type_institution'),
        ),
        migrations.AddField(
            model_name='event',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tym.Institution'),
        ),
    ]
