# Generated by Django 2.0.6 on 2018-06-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tym', '0003_auto_20180617_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_ticket',
            name='imprint',
        ),
    ]
