# Generated by Django 2.0.6 on 2018-06-17 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tym', '0004_remove_status_ticket_imprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status_ticket',
            options={},
        ),
        migrations.RemoveField(
            model_name='status_ticket',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='status_ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='status_ticket',
            name='status_ticket',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status_ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
